export const GET_ALBUMS_START = 'GET_ALBUMS_START'
export const GET_ALBUMS_SUCCESS = 'GET_ALBUMS_SUCCESS'
export const GET_ALBUMS_FAIL = 'GET_ALBUMS_FAIL'

export const GET_ALBUM_PHOTOS_START = 'GET_ALBUM_PHOTOS_START'
export const GET_ALBUM_PHOTOS_SUCCESS = 'GET_ALBUM_PHOTOS_SUCCESS'
export const GET_ALBUM_PHOTOS_FAIL = 'GET_ALBUM_PHOTOS_FAIL'
export const CLEAR_ALBUM_PHOTOS = 'CLEAR_ALBUM_PHOTOS'

export const GET__PHOTO_START = 'GET__PHOTO_START'
export const GET__PHOTO_SUCCESS = 'GET__PHOTO_SUCCESS'
export const GET__PHOTO_FAIL = 'GET__PHOTO_FAIL'
export const CLEAR__PHOTO = 'CLEAR__PHOTO'
